config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  # 'static' pages
  root 'static#index'

  get 'business' => 'static#business'
  get 'about' => 'static#about'
  get 'signed_up' => 'static#signed_up'

  post 'user_subscriptions' => 'user_subscriptions#create'

  # application-related routes
  devise_for :user, controllers: { sessions: 'users/sessions',
                                   registrations: 'users/registrations',
                                   passwords: 'users/passwords',
                                   confirmations: 'users/confirmations' }

  get 'app/accommodation_type' => 'planner#accommodation_type', as: 'planner_accommodation_type'
  get 'app/activity_type' => 'planner#activity_type', as: 'planner_activity_type'
  get 'app/hotels' => 'planner#hotels', as: 'planner_hotels'
  get 'app/hostels' => 'planner#hostels', as: 'planner_hostels'
  get 'app/apartments' => 'planner#apartments', as: 'planner_apartments'
  get 'app/activities' => 'planner#activities', as: 'planner_activities'
  get 'app/events' => 'planner#events', as: 'planner_events'
  get 'app/vehicles' => 'planner#vehicles', as: 'planner_vehicles'
  get 'app/planner_add_activity/:type/:id' => 'planner#add_activity', as: 'planner_add_activity'
  get 'app/planner_remove_activity/:type/:id' => 'planner#remove_activity', as: 'planner_remove_activity'
  get 'app/planner_add_accommodation/:id' => 'planner#add_accommodation', as: 'planner_add_accommodation'
  get 'app/planner_remove_accommodation' => 'planner#remove_accommodation', as: 'planner_remove_accommodation'
  get 'app/planner_new_session' => 'planner#new_session', as: 'planner_new_session' 
  get 'app/book' => 'planner#book', as: 'planner_book'
  get 'app/init' => 'planner#init', as: 'planner_init'
  get 'app(/:date/:destination)' => 'planner#list_chosen', as: 'planner_list_chosen'
  get 'app/get_service_details' => 'planner#get_service_details'
  get 'app/planner_edit_session' => 'planner#edit_session', as: 'planner_edit_session'
  post 'app/planner_update_session' => 'planner#update_session', as: 'planner_update_session'

  resource :user_profile

  # listings resources are used for browsing resources
  # does not support modifying or deleting
  resources :listings, only: [ :index, :show ]

  # user_listings resources are used for managing single users' listings:
  # creation, editing, listing, deleting, ...
  resources :user_listings, only: [ :index, :new, :show, :destroy, :edit ]

  resources  :message_threads, only: [ :index, :new, :create ] do
    resources :messages, only: [ :index, :show, :create ]
  end
  
  resources :reservations, only: [ :index, :show]
  get 'reservations/:id/accept' => 'reservations#accept',
      as: 'reservation_accept'
  get 'reservations/:id/reject' => 'reservations#reject',
      as: 'reservation_reject'
  get 'reservations/:id/cancel' => 'reservations#cancel',
      as: 'reservation_cancel'
  resources :reservation_packages, only: [ :show, :index ] do
    resources :reservations, only: [ :index, :show ]
    get 'reservation_packages/download' => 'reservation_packages#download', as: 'download'
  end

  resources :photographs, only: [ :update, :destroy ]

  # lodging providers and associated resources
  resources :hotels do
    shallow do
      resources :photographs, only: [ :create ]

      resources :rooms do
        resource :pricing_scheme, controller: 'room_pricing_schemes'
        resource :calendar, only: [ :show ]
        resources :calendar_intervals
        resource :photographs, only: [ :create, :update ]
      end
    end
  end

  resources :hostels do
    shallow do
      resource :photographs, only: [ :create ]

      resources :rooms do
        resource :pricing_scheme, controller: 'room_pricing_schemes'
        resource :calendar, only: [ :show ]
        resources :calendar_intervals
        resource :photographs, only: [ :create ]
      end
    end
  end

  resources :private_accommodations do
    shallow do
      resource :photographs, only: [ :create ],
               controller: 'private_accommodations', action: 'create_photograph'

      resources :rooms do
        resource :pricing_scheme, controller: 'room_pricing_schemes'
        resource :calendar, only: [ :show ]
        resources :calendar_intervals
        resource :photographs, only: [ :create, :update]
      end
    end
  end

  resources :lighthouses do
    shallow do
      resource :photographs, only: [ :create ]
      resource :calendar, only: [ :show ]
      resources :calendar_intervals
      resource :pricing_scheme, controller: 'lighthouse_pricing_schemes'
    end
  end

  resources :islands do
    shallow do
      resource :photographs, only: [ :create ]
      resource :calendar, only: [ :show ]
      resources :calendar_intervals
      resource :pricing_scheme, controller: 'island_pricing_schemes'
    end
  end

  resources :vehicles do
    shallow do
      resources :photographs, only: [ :create ]
    end
  end

  resources :rents do
    shallow do
      resource :photographs, only: [ :create ]
      resources :cars do
        resource :calendar, only: [ :show ]
        resource :pricing_scheme, controller: 'rent_pricing_schemes'
        resources :calendar_intervals
        resource :photographs, only: [ :create ]
      end
      resources :boats do
        resource :calendar, only: [ :show ]
        resource :pricing_scheme, controller: 'rent_pricing_schemes'
        resources :calendar_intervals
        resource :photographs, only: [ :create ]
      end
      resources :bikes do
        resource :calendar, only: [ :show ]
        resource :pricing_scheme, controller: 'rent_pricing_schemes'
        resources :calendar_intervals
        resource :photographs, only: [ :create ]
      end
      resources :motorbikes do
        resource :calendar, only: [ :show ]
        resource :pricing_scheme, controller: 'rent_pricing_schemes'
        resources :calendar_intervals
        resource :photographs, only: [ :create ]
      end
    end
  end

  # events
  resources :events do
    shallow do
      resource :photographs, only: [ :create ]
    end
  end

  # activities
  resources :activities do
    shallow do
      resource :photographs, only: [ :create ]
      resources :calendar_intervals
      resource :calendar, only: [ :show ]
      resource :pricing_scheme, controller: 'activity_pricing_schemes'
    end
  end

  # Charterers
  resources :charters do
    shallow do
      resource :photographs, only: [ :create ]
      resources :calendar_intervals
      resource :calendar, only: [ :show ]
      resource :pricing_scheme, controller: 'charter_pricing_schemes'
    end
  end

  get '/mangopay_webhook', :to => 'trips#mangopay_webhook'

  resources :payments

  # Trips
  resources :trips do
    member do
      get :list_chosen
      get :book
      get :mangopay_webhook
      get :reserve_payment
      post :register_card
    end
    resources :trip_destinations
  end

  resources :trip_destinations do
    member do
      get :accommodation_type
      get :activity_type
    end
    resources :trip_items, :only => [:index] do
      collection do
        get :add_accommodation
        get :add_activity
      end
    end
  end
  
  resources :trip_items, :only => [:show, :destroy]
  
  resources :cities, :only => [:index] do
    get :autocomplete_city_name, :on => :collection
  end

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user
  has_many :trip_destinations, dependent: :destroy
  accepts_nested_attributes_for :trip_destinations, reject_if: :all_blank, allow_destroy: true
  
  validates :no_of_guest, presence: :true
  
  scope :draft, -> { where(:active => false) }
  
  def create_reservation_package(user, url, card_id)
    payment = {}
    start_date = trip_destinations.pluck(:start_date).first
    last_date = trip_destinations.pluck(:end_date).last
    rp = ReservationPackage.new(user_id: user.id, date_from: start_date, date_to: last_date)
    if rp.save
      self.update_attributes(active: true)
      trip_items = TripItem.where("trip_destination_id IN (?)", trip_destinations.pluck(:id))
      trip_items.each do |trip_item|
        rp.reservations.create(
          reservable_id: trip_item.item_id,
          reservable_type: trip_item.item_type,
          date_from: trip_item.start_date,
          date_to: trip_item.end_date,
          number_of_people: trip_item.trip_destination.no_of_guest,
          price: trip_item.price
        )
      end
      payment = MangoPay::PreAuthorization.create({
        AuthorId: ENV['AUTHOR_ID'],
        DebitedFunds: { Currency: ENV['CURRENCY'], Amount: trip_items.sum(:price).to_i*100 },
        Fees: { Currency: ENV['CURRENCY'], Amount: 0 },
        CardId: card_id,
        SecureMode: 'DEFAULT',
        SecureModeReturnURL: "#{url}/reservation_packages/#{rp.id}/reservations",
        Tag: ENV['MANGOPAY_TAG']
      })
      # payment = MangoPay::PayIn::Card::Web.create({
      #   AuthorId: ENV['AUTHOR_ID'],
      #   CreditedUserId: ENV['CREDITED_USER_ID'],
      #   DebitedFunds: { Currency: ENV['CURRENCY'], Amount: trip_items.sum(:price).to_i },
      #   Fees: { Currency: ENV['CURRENCY'], Amount: 0 },
      #   CreditedWalletId: ENV['CREDITED_WALLET_ID'],
      #   ReturnURL: "#{url}/reservation_packages/#{rp.id}/reservations",
      #   CardType: ENV['CARD_TYPE'],
      #   Culture: ENV['CULTURE'],
      #   Tag: ENV['MANGOPAY_TAG']
      # })
      
      rp.create_payment(user, payment)
    end
    payment
  end
  
  def total_amount
    trip_items = TripItem.where("trip_destination_id IN (?)", trip_destinations.pluck(:id))
    trip_items.sum(:price).to_i
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  layout :set_layout
  #before_action :authenticate #, :authenticate_user!
  before_action :authenticate_user!, :only => [:book, :reserve_payment]

  def index
    @trips = current_user.trips.draft.order("id desc")
  end

  def new
    if current_user.present?
      trips = current_user.trips.draft
      if trips.count >= 4
        flash[:notice] = "Možete stvoriti samo četiri plana odjednom. Odaberite bilo kojeg da biste nastavili ili izbrisali planove na čekanju!"
        redirect_to trips_path
      else
        @trip = Trip.new
        @trip_destination = @trip.trip_destinations.build
      end
    else
      if !cookies[:trip].nil?
        cookies_trip = JSON.parse(cookies[:trip])
        if Trip.exists?(cookies_trip[0]["trip_id"]) 
          redirect_to edit_trip_path(cookies_trip[0]["trip_id"])
        end
      end
      @trip = Trip.new
      @trip_destination = @trip.trip_destinations.build
    end
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def create
    @trip = Trip.new(trip_params)
    if @trip.save
      if !current_user.present?
        @trip.update(expires: 1.week.from_now.to_datetime)
        cookies[:trip] = {:value => JSON.generate([trip_id: @trip.id]), :expires => 1.week.from_now }
      end
      redirect_to list_chosen_trip_path(@trip)
    else
      render 'new'
    end
  end

  def update
    @trip = Trip.find(params[:id])
    if @trip.update_attributes(trip_params)
      redirect_to list_chosen_trip_path(@trip)
    else
      render 'edit'
    end
  end
  
  def list_chosen
    @trip = Trip.includes(:trip_destinations).find(params[:id])
    @trip_destinations = @trip.trip_destinations
    @all_dates_destinations = @trip_destinations.collect_concat do |d|
      ts_range = Date.parse(d.start_date.strftime('%Y-%m-%d'))..Date.parse(d.end_date.strftime('%Y-%m-%d'))
      dates = ts_range.to_a
      dates.each.collect_concat do |date|
        { date: date, city_id: d.city_id, id: d[:id] }
      end
    end.sort do |a, b|
      a[:date] <=> b[:date]
    end
  end
  
  def reserve_payment
    @trip = Trip.find(params[:id])
  end
  
  def register_card
    # @trip = Trip.find(params[:id])
    @card_registration = CardRegistrationService.new(params[:id],current_user,root_url)
    pre_auth_payment_response = @card_registration.initiate_card_registration(register_card_params)
    if !pre_auth_payment_response["SecureModeRedirectURL"].nil?
      redirect_to pre_auth_payment_response["SecureModeRedirectURL"]
    else
      flash[:payment_error] = pre_auth_payment_response["ResultMessage"]
      redirect_to :back
    end    
  end
  
  # def book
  #   @trip = Trip.find(params[:id])
  #   response = @trip.create_reservation_package(current_user, root_url)
  #   if !response["SecureModeRedirectURL"].nil?
  #     redirect_to response["SecureModeRedirectURL"]
  #   else
  #     flash[:payment_error] = response["ResultMessage"]
  #     redirect_to :back
  #   end
  # end

  def mangopay_webhook
    if !params.empty?
      # payment_response = MangoPay::PreAuthorization.fetch(params["preAuthorizationId"])
      render text: "Success"
    else
      render text: "Transaction Failed!"
    end
    # if !params.empty?
    #   payment_response = MangoPay::PayIn.fetch(params["RessourceId"])
    #   payment = Payment.find_by(transaction_id: params["RessourceId"])
    #   payment.update(event_type: params["EventType"], payment_status: payment_response["Status"])
      
    #   if payment.payment_status == "SUCCEEDED"
    #     generate_pdf(payment.invoice)
    #   end
      
    #   render text: "Success"
    # else
    #   render text: "Transaction Failed!"
    # end
  end

  def generate_pdf(invoice)
    pdf_kit = PDFKit.new(as_html(invoice.id), page_size: 'A4')
    pdf_kit.to_file("#{Rails.root}/public/invoice-#{invoice.payment.transaction_id}.pdf")
    file = File.open("#{Rails.root}/public/invoice-#{invoice.payment.transaction_id}.pdf")
    invoice_attachment = invoice.photographs.new(photograph_file_name: "#{invoice.payment.transaction_id}.pdf")
    invoice_attachment.photograph = file
    invoice_attachment.save
    if invoice_attachment.save
      UserMailer.send_invoice(invoice.payment.user_id, invoice.id).deliver_now
      File.delete(file) if File.exist?(file)
    end
  end

  def as_html(id)
    @invoice = Invoice.find(id)
    render_to_string template: "payments/invoice_template.html.erb", layout: "invoice"
  end
  
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    redirect_to trips_path  
  end

  protected
  
  def trip_params
    params.require(:trip).permit(:no_of_guest, :start_date, :end_date, trip_destinations_attributes: [:id, :start_date, :end_date, :city_id, :no_of_guest, :_destroy]).merge(user_id: current_user.present? ? current_user.id : nil )
  end

  def register_card_params
    params.permit(:username, :card_number, :month, :year, :cvv)
  end
  # def authenticate
  #   authenticate_or_request_with_http_basic do |id, password| 
  #      id == USER_ID && password == PASSWORD
  #   end
  # end

  def set_layout
    (params[:action] == "index") ? "user_profile" : "new_trip"
  end
  
end

app/helpers/trips_helper.rb
module TripsHelper

  def get_destination(id)
    @destination = TripDestination.find(id)
  end

  def get_accomodation(destination_id)
    @accommodation = TripItem.where("trip_destination_id = ? AND item_type IN (?)", destination_id, ['Room','Island','Lighthouse','Charter']).last
  end

  def get_activities(destination_id)
    @activities = TripItem.where("trip_destination_id = ? AND item_type IN (?)", destination_id, ['Activity','Event','Car','Bike', 'Motorbike', 'Boat'])
  end

  def get_trip_image_name(obj)
    if obj.item_type == 'Activity'
      'icon-excursion.png'
    elsif obj.item_type == 'Event'
      'icon-sport.png'
    else
      'icon-rent.png'
    end
  end

  def get_trip_accom_img(obj)
    if obj.item_type == 'Lighthouse'
      icon = 'icon-lighthouse.png'
    elsif obj.item_type == 'Island'
      icon = 'icon-island.png'
    elsif obj.item_type == 'Charter'
      icon = 'chartered.png'
    elsif obj.item_type == 'Room'
      room = Room.find(obj.item_id)
      icon = 'icon-apartments.png' if room.lodging_provider_type == 'PrivateAccommodation'
      icon = 'icon-hotel.png' if room.lodging_provider_type == 'Hotel'
      icon = 'icon-hostel.png' if room.lodging_provider_type == 'Hostel'
    end
    return icon
  end

  def arranged_trip_activities(activities, d)
    arranged_activities = []
    acts = activities.select{|a| a.item_type == 'Activity' && d[:date] == a.start_date && a.trip_destination.city_id == d[:city_id]}
    events = activities.select{|a| a.item_type == 'Event' && d[:date] == a.start_date && a.trip_destination.city_id == d[:city_id]}
    others = activities.select{|a| ['Activity', 'Event'].exclude?(a.item_type) && d[:date] == a.start_date && a.trip_destination.city_id == d[:city_id]}
    acts.each{|a| arranged_activities.push(a)}
    events.each{|e| arranged_activities.push(e)}
    others.each{|o| arranged_activities.push(o)}
    count = arranged_activities.count
    count < 3 ? (3 - count).to_i.times { arranged_activities.push(nil) } : (count+1 - count).to_i.times { arranged_activities.push(nil) }
    arranged_activities
  end

end

app/views/trips/_trip_destination_fields.html.erb
<div class="nested-fields">
  <div class="guest">
    <div class="dest-field">
      <%= autocomplete_field_tag 'city', '', autocomplete_city_name_cities_path, placeholder: 'City', required: true, value: "#{f.object.city.name rescue ''}", class: 'auto_city' %>
      <%= f.hidden_field :city_id %>
    </div>
    <div class="dest-field">
      <%= f.text_field :start_date, class: 'dest-start-date', placeholder: 'Check in', required: true %>
    </div>
    <div class="dest-field">
      <%= f.text_field :end_date, class: 'dest-end-date', placeholder: 'Check out', required: true %>
    </div>
  </div>
  <div class="guest">
    <%= link_to_remove_association "Remove", f, class: "remove" %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function () {
    $('.auto_city').keyup(function(){
      var term = $(this).val();
      for(i=0; i < $(".ui-menu-item").length ; i++){
        if($($(".ui-menu-item")[i]).find('div').text().toLowerCase() == term.toLocaleLowerCase()){
          $($(".ui-menu-item")[i]).find('div').trigger('click');
        }
      }
    });
    $('input').bind('railsAutocomplete.select', function(event, data){
      $(this).next().val(data.item.id);
    });
    var fmt = 'YYYY-MM-DD';
    var tomorrow = '';
    var today = moment().format(fmt);
    $('.dest-end-date').datepicker({minDate: today});
    $('.dest-start-date').datepicker({
      minDate: today, 
      onSelect: function(dateText, inst) {
        var date = $(this).val();
        $(this).parent().next('.dest-field').find('.dest-end-date').val(date);
      }
    });

    $('.dest-start-date, .dest-end-date').on('click, focus',datePicker);
    
    function datePicker(){
      var selected_date = new Date();
      month = $('.ui-datepicker-title').find('.ui-datepicker-month').text();
      year = $('.ui-datepicker-title').find('.ui-datepicker-year').text();
      selected_date = new Date(year+' '+month+' '+"01");

      $('.dest-start-date').attr('data-event','');
      $('.dest-end-date').attr('data-event','');
      if ($(this).hasClass('dest-start-date')){
        $(this).attr('data-event', 'clicked');
        $(this).parent().next('.dest-field').find('input').attr('data-event', 'clicked');
        var current_start_date = $(this).val();
        var current_end_date = $(this).parent().next('.dest-field').find('input').val();
        edate = new Date(current_end_date);
        sdate = new Date(current_start_date);        
        if ((edate.getDate() < sdate.getDate()) && (edate.getMonth()+1 == sdate.getMonth()+1)){
          if(edate.getDate().toString() == $('.ui-datepicker-current-day').children().text()){
            $('.ui-datepicker-current-day').children().removeClass('ui-state-active');
          }
          $(this).parent().next('.dest-field').find('input').val(current_start_date);
          current_end_date = current_start_date;
        }
        colorSelectedDateRange(current_start_date, current_end_date, selected_date);
      }
      else {
        $(this).attr('data-event', 'clicked');
        $(this).parent().prev('.dest-field').find('input').attr('data-event', 'clicked');
        var current_start_date = $(this).parent().prev('.dest-field').find('input').val();
        var current_end_date = $(this).val();
        edate = new Date(current_end_date);
        sdate = new Date(current_start_date);
        if ((edate.getDate() < sdate.getDate()) && (edate.getMonth()+1 == sdate.getMonth()+1)){
          if(edate.getDate().toString() == $('.ui-datepicker-current-day').children().text()){
            $('.ui-datepicker-current-day').children().removeClass('ui-state-active');
          }
          $(this).val(current_start_date);
          current_end_date = current_start_date;
        }
        colorSelectedDateRange(current_start_date, current_end_date, selected_date);
      }
    }
    $(document).on('click, focus', '.ui-datepicker-next, .ui-datepicker-prev', function () {
      current_start_date = $('.dest-start-date[data-event="clicked"]').val();
      current_end_date = $('.dest-end-date[data-event="clicked"]').val();
      edate = new Date(current_end_date);
      sdate = new Date(current_start_date);
      if ((edate.getDate() < sdate.getDate()) && (edate.getMonth()+1 == sdate.getMonth()+1)) {
        if(edate.getDate().toString() == $('.ui-datepicker-current-day').children().text()){
          $('.ui-datepicker-current-day').children().removeClass('ui-state-active');
        }
        $('.dest-end-date[data-event="clicked"]').val(current_start_date);
        current_end_date = current_start_date;
      }
      month = $('.ui-datepicker-title').find('.ui-datepicker-month').text();
      year = $('.ui-datepicker-title').find('.ui-datepicker-year').text()
      selected_date = new Date(year+' '+month+' '+"01");
      colorSelectedDateRange(current_start_date, current_end_date, selected_date);
    })
    var getDaysInMonth = function(month,year) {
      // Here January is 1 based
      //Day 0 is the last day in the previous month
      return new Date(year, month, 0).getDate();
      // Here January is 0 based
      // return new Date(year, month+1, 0).getDate();
    };
    function colorSelectedDateRange(current_start_date,current_end_date,selected_date){
      if (current_start_date != '' && current_end_date !=''){
        current_date_range = getDateArray(current_start_date,current_end_date);
      }else{
        current_date_range = [current_start_date,current_end_date];
      }
      
      current_month = selected_date.getMonth()+1;
      current_year = selected_date.getFullYear();
      days_in_selected_month = getDaysInMonth(current_month, current_year);

      for(j=0; j < current_date_range.length; j++){
        selected_month = parseInt(current_date_range[j].split('-')[1]);
        selected_day = parseInt(current_date_range[j].split('-')[2]);
        var color = '#ED365B';
        var disabled = false;
        colorSelectedMonthDates(days_in_selected_month, current_month, selected_day,selected_month,color,disabled);
      }
      for (i = 0; i < $('#trip_destinations').find('.nested-fields').length; i++) {
        start_date = $('#trip_destinations').find('.dest-start-date')[i].value
        end_date = $('#trip_destinations').find('.dest-end-date')[i].value
        if(start_date != current_start_date && end_date != current_end_date){
          date_array = getDateArray(start_date,end_date);
          for(j=0; j < date_array.length; j++){
            selected_month = parseInt(date_array[j].split('-')[1]);
            selected_day = parseInt(date_array[j].split('-')[2]);
            var color = 'rgb(199, 85, 108)';
            var disabled = true;
            colorSelectedMonthDates(days_in_selected_month, current_month, selected_day,selected_month,color,disabled);
          }
        }
      }
    }
    function colorSelectedMonthDates(days_in_selected_month, month, selected_day,selected_month, color, disabled){
      for(k=0; k < days_in_selected_month; k++){
        if ($($('.ui-datepicker-calendar tbody tr td').not('.ui-datepicker-other-month')[k])[0].firstChild !== undefined){
          day = parseInt($($('.ui-datepicker-calendar tbody tr td').not('.ui-datepicker-other-month')[k])[0].firstChild.innerText);
          if(month !== undefined && day !== undefined){
            if(month == selected_month && day == selected_day){
              if(disabled){
                $($('.ui-datepicker-calendar tbody tr td').not('.ui-datepicker-other-month')[k]).addClass('ui-state-disabled');
              }
              if($($('.ui-datepicker-calendar tbody tr td').not('.ui-datepicker-other-month')[k]).find('a').length == 0){
                $($('.ui-datepicker-calendar tbody tr td').not('.ui-datepicker-other-month')[k]).find('span').attr('style', 'background-color: '+color+' !important; color: #fff;');
              }else{
                $($('.ui-datepicker-calendar tbody tr td').not('.ui-datepicker-other-month')[k]).find('a').attr('style', 'background-color: '+color+' !important; color: #fff;');
              }
            }
          }
        }
      }
    }
    function getDateArray(startDate, stopDate) {
      var dateArray = [];
      var currentDate = moment(startDate);
      var stopDate = moment(stopDate);
      while (currentDate <= stopDate) {
        dateArray.push( moment(currentDate).format('YYYY-MM-DD') )
        currentDate = moment(currentDate).add(1, 'days');
      }
      return dateArray;
    }

    $('#trip_destinations').on('cocoon:after-insert', function() {
      last_dates = $('.dest-end-date').toArray();      
      new_end_date = $(last_dates[last_dates.length - 2]).val();
      date = moment(new_end_date).add(1, 'days')
      $('.dest-start-date').last().val(moment(date).format('YYYY-MM-DD'));
      $('.dest-end-date').last().val(moment(date).format('YYYY-MM-DD'));
    });
  });
</script>

app/views/trips/edit.html.erb
<%= render 'form' %>

app/views/trips/index.html.erb
<div class="container-fluid">
  <%= render 'shared/messages' %>
</div>

<div class="container-fluid">
  <div class="main-table">
    <table width="100%">
      <thead>
        <tr>
          <th>Details</th>
          <th>Active</th>
          <th>Created at</th>
          <th>Radnja</th>
        </tr>
      </thead>
      <tbody>
        <% unless @trips.blank? %>
          <% @trips.each do |trip| %>
            <tr>
              <td>
                <% trip.trip_destinations.each do |destinations| %>
                  <%= destinations.city.name+", From "+destinations.start_date.strftime("%Y-%m-%d")+ " To "+destinations.end_date.strftime("%Y-%m-%d")+ " With "+trip.no_of_guest.to_s+ " Guest" %><br>
                <% end %>
              </td>
              <td><%= label_tag(trip.active) %></td>
              <td><%= trip.created_at.strftime('%Y-%m-%d') %></td>
              <td>
                <% unless trip.active %>
                  <%= link_to 'Resume', edit_trip_path(trip), class: "table_anchor" %>
                     | <%= link_to 'Delete', trip_path(trip), method: 'delete', :data => {:confirm => 'Are you sure?'}, class: "table_anchor_delete" %>
                <% else %>
                  <%= link_to 'View', list_chosen_trip_path(trip), class: "table_anchor" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% else %>
          <tr><td colspan="4"> No trip found </td></tr>
        <% end %>  
      </tbody>
    </table>
  </div>
</div>

app/views/trips/new.html.erb
<%= render 'form' %>