config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  # 'static' pages
  root 'static#index'

  get 'business' => 'static#business'
  get 'about' => 'static#about'
  get 'signed_up' => 'static#signed_up'

  post 'user_subscriptions' => 'user_subscriptions#create'

  # application-related routes
  devise_for :user, controllers: { sessions: 'users/sessions',
                                   registrations: 'users/registrations',
                                   passwords: 'users/passwords',
                                   confirmations: 'users/confirmations' }

  get 'app/accommodation_type' => 'planner#accommodation_type', as: 'planner_accommodation_type'
  get 'app/activity_type' => 'planner#activity_type', as: 'planner_activity_type'
  get 'app/hotels' => 'planner#hotels', as: 'planner_hotels'
  get 'app/hostels' => 'planner#hostels', as: 'planner_hostels'
  get 'app/apartments' => 'planner#apartments', as: 'planner_apartments'
  get 'app/activities' => 'planner#activities', as: 'planner_activities'
  get 'app/events' => 'planner#events', as: 'planner_events'
  get 'app/vehicles' => 'planner#vehicles', as: 'planner_vehicles'
  get 'app/planner_add_activity/:type/:id' => 'planner#add_activity', as: 'planner_add_activity'
  get 'app/planner_remove_activity/:type/:id' => 'planner#remove_activity', as: 'planner_remove_activity'
  get 'app/planner_add_accommodation/:id' => 'planner#add_accommodation', as: 'planner_add_accommodation'
  get 'app/planner_remove_accommodation' => 'planner#remove_accommodation', as: 'planner_remove_accommodation'
  get 'app/planner_new_session' => 'planner#new_session', as: 'planner_new_session' 
  get 'app/book' => 'planner#book', as: 'planner_book'
  get 'app/init' => 'planner#init', as: 'planner_init'
  get 'app(/:date/:destination)' => 'planner#list_chosen', as: 'planner_list_chosen'
  get 'app/get_service_details' => 'planner#get_service_details'
  get 'app/planner_edit_session' => 'planner#edit_session', as: 'planner_edit_session'
  post 'app/planner_update_session' => 'planner#update_session', as: 'planner_update_session'

  resource :user_profile

  # listings resources are used for browsing resources
  # does not support modifying or deleting
  resources :listings, only: [ :index, :show ]

  # user_listings resources are used for managing single users' listings:
  # creation, editing, listing, deleting, ...
  resources :user_listings, only: [ :index, :new, :show, :destroy, :edit ]

  resources  :message_threads, only: [ :index, :new, :create ] do
    resources :messages, only: [ :index, :show, :create ]
  end
  
  resources :reservations, only: [ :index, :show]
  get 'reservations/:id/accept' => 'reservations#accept',
      as: 'reservation_accept'
  get 'reservations/:id/reject' => 'reservations#reject',
      as: 'reservation_reject'
  get 'reservations/:id/cancel' => 'reservations#cancel',
      as: 'reservation_cancel'
  resources :reservation_packages, only: [ :show, :index ] do
    resources :reservations, only: [ :index, :show ]
    get 'reservation_packages/download' => 'reservation_packages#download', as: 'download'
  end

  resources :photographs, only: [ :update, :destroy ]

  # lodging providers and associated resources
  resources :hotels do
    shallow do
      resources :photographs, only: [ :create ]

      resources :rooms do
        resource :pricing_scheme, controller: 'room_pricing_schemes'
        resource :calendar, only: [ :show ]
        resources :calendar_intervals
        resource :photographs, only: [ :create, :update ]
      end
    end
  end

  resources :hostels do
    shallow do
      resource :photographs, only: [ :create ]

      resources :rooms do
        resource :pricing_scheme, controller: 'room_pricing_schemes'
        resource :calendar, only: [ :show ]
        resources :calendar_intervals
        resource :photographs, only: [ :create ]
      end
    end
  end

  resources :private_accommodations do
    shallow do
      resource :photographs, only: [ :create ],
               controller: 'private_accommodations', action: 'create_photograph'

      resources :rooms do
        resource :pricing_scheme, controller: 'room_pricing_schemes'
        resource :calendar, only: [ :show ]
        resources :calendar_intervals
        resource :photographs, only: [ :create, :update]
      end
    end
  end

  resources :lighthouses do
    shallow do
      resource :photographs, only: [ :create ]
      resource :calendar, only: [ :show ]
      resources :calendar_intervals
      resource :pricing_scheme, controller: 'lighthouse_pricing_schemes'
    end
  end

  resources :islands do
    shallow do
      resource :photographs, only: [ :create ]
      resource :calendar, only: [ :show ]
      resources :calendar_intervals
      resource :pricing_scheme, controller: 'island_pricing_schemes'
    end
  end

  resources :vehicles do
    shallow do
      resources :photographs, only: [ :create ]
    end
  end

  resources :rents do
    shallow do
      resource :photographs, only: [ :create ]
      resources :cars do
        resource :calendar, only: [ :show ]
        resource :pricing_scheme, controller: 'rent_pricing_schemes'
        resources :calendar_intervals
        resource :photographs, only: [ :create ]
      end
      resources :boats do
        resource :calendar, only: [ :show ]
        resource :pricing_scheme, controller: 'rent_pricing_schemes'
        resources :calendar_intervals
        resource :photographs, only: [ :create ]
      end
      resources :bikes do
        resource :calendar, only: [ :show ]
        resource :pricing_scheme, controller: 'rent_pricing_schemes'
        resources :calendar_intervals
        resource :photographs, only: [ :create ]
      end
      resources :motorbikes do
        resource :calendar, only: [ :show ]
        resource :pricing_scheme, controller: 'rent_pricing_schemes'
        resources :calendar_intervals
        resource :photographs, only: [ :create ]
      end
    end
  end

  # events
  resources :events do
    shallow do
      resource :photographs, only: [ :create ]
    end
  end

  # activities
  resources :activities do
    shallow do
      resource :photographs, only: [ :create ]
      resources :calendar_intervals
      resource :calendar, only: [ :show ]
      resource :pricing_scheme, controller: 'activity_pricing_schemes'
    end
  end

  # Charterers
  resources :charters do
    shallow do
      resource :photographs, only: [ :create ]
      resources :calendar_intervals
      resource :calendar, only: [ :show ]
      resource :pricing_scheme, controller: 'charter_pricing_schemes'
    end
  end

  get '/mangopay_webhook', :to => 'trips#mangopay_webhook'

  resources :payments

  # Trips
  resources :trips do
    member do
      get :list_chosen
      get :book
      get :mangopay_webhook
      get :reserve_payment
      post :register_card
    end
    resources :trip_destinations
  end

  resources :trip_destinations do
    member do
      get :accommodation_type
      get :activity_type
    end
    resources :trip_items, :only => [:index] do
      collection do
        get :add_accommodation
        get :add_activity
      end
    end
  end
  
  resources :trip_items, :only => [:show, :destroy]
  
  resources :cities, :only => [:index] do
    get :autocomplete_city_name, :on => :collection
  end

end

app/models/trip_item.rb
class TripItem < ActiveRecord::Base
  belongs_to :trip_destination
end

app/controllers/trip_items_controller.rb
class TripItemsController < ApplicationController
  layout "new_trip"

  def index
  end

  def show
    @trip_destination = TripDestination.find(params[:trip_destination_id])
    @destination = params[:destination]
    @ts_range = params[:ts_range]
    date_range = @ts_range.split("..")
    if params[:item_type] == "Room" || params[:item_type] == "Island" || params[:item_type] == "Lighthouse" || params[:item_type] == "Charter"
      @accommodation = @trip_destination.trip_items.find(params[:id])
      @accommodation_details = @accommodation.item_type.constantize.find(@accommodation.item_id)
      render :partial => 'accommodation'
    else
      @activity = @trip_destination.trip_items.find(params[:id])
      @activity_details = @activity.item_type.constantize.find(@activity.item_id)
      render :partial => 'activity_details'
    end
  end
  
  def destroy
    trip_item = TripItem.find(params[:id])
    trip_item.destroy
    redirect_to list_chosen_trip_path(trip_item.trip_destination.trip)
  end

  def add_accommodation
    @trip_destination = TripDestination.find(params[:trip_destination_id])
    add_accommodation_item params[:listing_type], params[:listing_id], params[:trip_destination_id], params[:ts_range]
    redirect_to list_chosen_trip_path(@trip_destination.trip)
  end

  def add_activity
    @trip_destination = TripDestination.find(params[:trip_destination_id])
    add_activity_item params[:listing_type], params[:listing_id], params[:trip_destination_id], params[:date]
    redirect_to list_chosen_trip_path(@trip_destination.trip)
  end

  def add_accommodation_item(type, id, trip_destination_id, ts_range)
    dates = ts_range.split("..")
    obj = type.constantize.find(id)
    price = ReservablePriceQuery.new(obj).get_price(dates[0].to_date..dates[1].to_date)
    @trip_item = TripItem.create(item_type: type, item_id: id, price: price, trip_destination_id: trip_destination_id, start_date:dates[0].to_date, end_date:dates[1].to_date)
  end

  def add_activity_item(type, id, trip_destination_id, date)
    if type == 'Event'
      ci = Event.find(id)
      price = ci.base_rate
    else
      ci = type.constantize.find(id).calendar_intervals.includes(:schemable).containing_date(date.to_date)
      price = ci.last.schemable.base_rate
    end
    @trip_item = TripItem.create(item_type: type, item_id: id, price: price, trip_destination_id: trip_destination_id, start_date: date.to_date, end_date: date.to_date)
  end

  protected

  def trip_params
    params.require(:trip_destination).permit(:start_date, :end_date, :destination, :no_of_guest)
  end

end

app/views/trip_items/_accommodation.html.erb
<div class="image planner_right_img">
	<% img_url = @accommodation_details.photographs[0].photograph.url(:regular) rescue "" %>
  <%= image_tag img_url, class: 'planner_img' %>
</div>
<div class="planner_plus_txt">
  <div class="planner_l_img">
    <img src="<%= asset_path('profile_user.jpg') %>" class="p_img">
    <span class="planner_name">
      lvana
    </span>
  </div>
  <div class="planner_r_txt">
    <h3 class="p_bold_txt"><%= @accommodation_details.name %></h3>
    <p class="planner_sb_hed"><%= @accommodation_details.class.name == 'Room' ? @accommodation_details.lodging_provider.address.full_address : @accommodation_details.address.full_address %></p>
    <div class="rating_bdy">
      <ul class="star_list">
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star"></i></li>
      </ul>
      <span class="planner_memories"> 32 memories</span>
    </div>
  </div>
</div>
<div class="mail_btn">
  <a href="javascript:void(0);">
  <i class="fa fa-envelope-o"></i> <span class="btn_spn">Contact Host</span>
  </a>
</div>
<div class="availablity_list">
  <div class="availablity_list_left">
    <p>Stay type : <span> Room</span></p>
    <p>Stay :<span> <%= (@ts_range.split('..').last.to_date - @ts_range.split('..').first.to_date).to_i+1 %> days</span></p>
    <p>Guests : <span> 2</span></p>
  </div>

  <% if @accommodation_details.class.name == 'Room' %>
    <div class="availablity_list_right">
      <p>Bathrooms : <span><%= (@accommodation_details.bathroom.to_i rescue 0 ) + (@accommodation_details.shared_bathroom.to_i rescue 0) + (@accommodation_details.guest_bathroom.to_i rescue 0) %></span></p>
      <p>Bedrooms :<span> 2</span></p>
      <p>Beds : <span> <%= (@accommodation_details.single_beds.to_i rescue 0) + (@accommodation_details.double_beds.to_i rescue 0) + (@accommodation_details.queen_beds.to_i rescue 0) + (@accommodation_details.king_beds.to_i rescue 0) + (@accommodation_details.bunk_beds.to_i rescue 0) + (@accommodation_details.sofa_beds.to_i rescue 0) %></span></p>
    </div>
  <% end %>
</div>
<div class="planner_grey5">
  <ul>
    <li style="width: 50%">
      <span class="add_panner5">
        <%= link_to 'Cancel', trip_item_path(@accommodation.id), method: 'delete', :data => {:confirm => 'Are you sure?'} %>
      </span>
    </li>
    <li style="width: 50%">
      <span class="add_panner5">
      <a href="#" > Total Coast: €<%= @accommodation.price %> </a>
      </span>
    </li>
  </ul>
</div>

app/views/trip_items/_activity_details.html.erb
<div class="image planner_right_img">
	<% img_url = @activity_details.photographs[0].photograph.url(:regular) rescue "" %>
  <%= image_tag img_url, class: 'planner_img' %>
</div>
<div class="planner_plus_txt">
  <div class="planner_l_img">
    <img src="<%= asset_path('profile_user.jpg') %>" class="p_img">
    <span class="planner_name">
      lvana
    </span>
  </div>
  <div class="planner_r_txt">
    <h3 class="p_bold_txt"><%= @activity_details.name %></h3>
    <p class="planner_sb_hed"><%= @activity_details.address.full_address %></p>
    <div class="rating_bdy">
      <ul class="star_list">
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star"></i></li>
        <li><i class="fa fa-star"></i></li>
      </ul>
      <span class="planner_memories"> 32 memories</span>
    </div>
  </div>
</div>
<div class="mail_btn">
  <a href="javascript:void(0);">
  <i class="fa fa-envelope-o"></i> <span class="btn_spn">Contact Host</span>
  </a>
</div>

<div class="planner_grey5">
  <ul>
    <li class="mr_30px">
      <span class="add_panner5">
        <%= link_to 'Cancel', trip_item_path(@activity.id), method: 'delete', :data => {:confirm => 'Are you sure?'} %>
      </span>
    </li>
    <li class="mr_58">
      <span class="add_panner5">
      <a href="#" > Total Coast: €<%= @activity.price.to_s%> </a>
      </span>
    </li>
  </ul>
</div>
</div>