config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  # 'static' pages
  root 'static#index'

  get 'business' => 'static#business'
  get 'about' => 'static#about'
  get 'signed_up' => 'static#signed_up'

  post 'user_subscriptions' => 'user_subscriptions#create'

  # application-related routes
  devise_for :user, controllers: { sessions: 'users/sessions',
                                   registrations: 'users/registrations',
                                   passwords: 'users/passwords',
                                   confirmations: 'users/confirmations' }

  get 'app/accommodation_type' => 'planner#accommodation_type', as: 'planner_accommodation_type'
  get 'app/activity_type' => 'planner#activity_type', as: 'planner_activity_type'
  get 'app/hotels' => 'planner#hotels', as: 'planner_hotels'
  get 'app/hostels' => 'planner#hostels', as: 'planner_hostels'
  get 'app/apartments' => 'planner#apartments', as: 'planner_apartments'
  get 'app/activities' => 'planner#activities', as: 'planner_activities'
  get 'app/events' => 'planner#events', as: 'planner_events'
  get 'app/vehicles' => 'planner#vehicles', as: 'planner_vehicles'
  get 'app/planner_add_activity/:type/:id' => 'planner#add_activity', as: 'planner_add_activity'
  get 'app/planner_remove_activity/:type/:id' => 'planner#remove_activity', as: 'planner_remove_activity'
  get 'app/planner_add_accommodation/:id' => 'planner#add_accommodation', as: 'planner_add_accommodation'
  get 'app/planner_remove_accommodation' => 'planner#remove_accommodation', as: 'planner_remove_accommodation'
  get 'app/planner_new_session' => 'planner#new_session', as: 'planner_new_session' 
  get 'app/book' => 'planner#book', as: 'planner_book'
  get 'app/init' => 'planner#init', as: 'planner_init'
  get 'app(/:date/:destination)' => 'planner#list_chosen', as: 'planner_list_chosen'
  get 'app/get_service_details' => 'planner#get_service_details'
  get 'app/planner_edit_session' => 'planner#edit_session', as: 'planner_edit_session'
  post 'app/planner_update_session' => 'planner#update_session', as: 'planner_update_session'

  resource :user_profile

  # listings resources are used for browsing resources
  # does not support modifying or deleting
  resources :listings, only: [ :index, :show ]

  # user_listings resources are used for managing single users' listings:
  # creation, editing, listing, deleting, ...
  resources :user_listings, only: [ :index, :new, :show, :destroy, :edit ]

  resources  :message_threads, only: [ :index, :new, :create ] do
    resources :messages, only: [ :index, :show, :create ]
  end
  
  resources :reservations, only: [ :index, :show]
  get 'reservations/:id/accept' => 'reservations#accept',
      as: 'reservation_accept'
  get 'reservations/:id/reject' => 'reservations#reject',
      as: 'reservation_reject'
  get 'reservations/:id/cancel' => 'reservations#cancel',
      as: 'reservation_cancel'
  resources :reservation_packages, only: [ :show, :index ] do
    resources :reservations, only: [ :index, :show ]
    get 'reservation_packages/download' => 'reservation_packages#download', as: 'download'
  end

  resources :photographs, only: [ :update, :destroy ]

  # lodging providers and associated resources
  resources :hotels do
    shallow do
      resources :photographs, only: [ :create ]

      resources :rooms do
        resource :pricing_scheme, controller: 'room_pricing_schemes'
        resource :calendar, only: [ :show ]
        resources :calendar_intervals
        resource :photographs, only: [ :create, :update ]
      end
    end
  end

  resources :hostels do
    shallow do
      resource :photographs, only: [ :create ]

      resources :rooms do
        resource :pricing_scheme, controller: 'room_pricing_schemes'
        resource :calendar, only: [ :show ]
        resources :calendar_intervals
        resource :photographs, only: [ :create ]
      end
    end
  end

  resources :private_accommodations do
    shallow do
      resource :photographs, only: [ :create ],
               controller: 'private_accommodations', action: 'create_photograph'

      resources :rooms do
        resource :pricing_scheme, controller: 'room_pricing_schemes'
        resource :calendar, only: [ :show ]
        resources :calendar_intervals
        resource :photographs, only: [ :create, :update]
      end
    end
  end

  resources :lighthouses do
    shallow do
      resource :photographs, only: [ :create ]
      resource :calendar, only: [ :show ]
      resources :calendar_intervals
      resource :pricing_scheme, controller: 'lighthouse_pricing_schemes'
    end
  end

  resources :islands do
    shallow do
      resource :photographs, only: [ :create ]
      resource :calendar, only: [ :show ]
      resources :calendar_intervals
      resource :pricing_scheme, controller: 'island_pricing_schemes'
    end
  end

  resources :vehicles do
    shallow do
      resources :photographs, only: [ :create ]
    end
  end

  resources :rents do
    shallow do
      resource :photographs, only: [ :create ]
      resources :cars do
        resource :calendar, only: [ :show ]
        resource :pricing_scheme, controller: 'rent_pricing_schemes'
        resources :calendar_intervals
        resource :photographs, only: [ :create ]
      end
      resources :boats do
        resource :calendar, only: [ :show ]
        resource :pricing_scheme, controller: 'rent_pricing_schemes'
        resources :calendar_intervals
        resource :photographs, only: [ :create ]
      end
      resources :bikes do
        resource :calendar, only: [ :show ]
        resource :pricing_scheme, controller: 'rent_pricing_schemes'
        resources :calendar_intervals
        resource :photographs, only: [ :create ]
      end
      resources :motorbikes do
        resource :calendar, only: [ :show ]
        resource :pricing_scheme, controller: 'rent_pricing_schemes'
        resources :calendar_intervals
        resource :photographs, only: [ :create ]
      end
    end
  end

  # events
  resources :events do
    shallow do
      resource :photographs, only: [ :create ]
    end
  end

  # activities
  resources :activities do
    shallow do
      resource :photographs, only: [ :create ]
      resources :calendar_intervals
      resource :calendar, only: [ :show ]
      resource :pricing_scheme, controller: 'activity_pricing_schemes'
    end
  end

  # Charterers
  resources :charters do
    shallow do
      resource :photographs, only: [ :create ]
      resources :calendar_intervals
      resource :calendar, only: [ :show ]
      resource :pricing_scheme, controller: 'charter_pricing_schemes'
    end
  end

  get '/mangopay_webhook', :to => 'trips#mangopay_webhook'

  resources :payments

  # Trips
  resources :trips do
    member do
      get :list_chosen
      get :book
      get :mangopay_webhook
      get :reserve_payment
      post :register_card
    end
    resources :trip_destinations
  end

  resources :trip_destinations do
    member do
      get :accommodation_type
      get :activity_type
    end
    resources :trip_items, :only => [:index] do
      collection do
        get :add_accommodation
        get :add_activity
      end
    end
  end
  
  resources :trip_items, :only => [:show, :destroy]
  
  resources :cities, :only => [:index] do
    get :autocomplete_city_name, :on => :collection
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Croffers</title>

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <%= csrf_meta_tags %>
    <%= render 'shared/ga' %>
 </head>

  <body>
    <%= render 'shared/navbar' %>

    <div id="planner">
      <div id="panel-left">
        <%= yield %>
      </div>
      <div id="panel-right">
        <div id="map"></div>
      </div>
    </div>
         
    <script type="text/javascript">
      var markers = L.markerClusterGroup({animate: false});
      var map = L.map('map', { center: [44.5435052132082, 16.50146484375],
      zoom: 6});

      L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap</a> contributors'
      }).addTo(map);

     $(window).on('load', function () {
       map.addLayer(markers);
     });
    </script>
  </body>
</html>

app/views/layouts/invoice.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <title>Invoice PDF</title>
    <meta charset="utf-8"/>
    <meta content="0.25in" name="pdfkit-margin_top"/>
    <meta content="0.25in" name="pdfkit-margin_right"/>
    <meta content="0.25in" name="pdfkit-margin_bottom"/>
    <meta content="0.25in" name="pdfkit-margin_left"/>
  </head>
  <style>
    
    .clearfix:after {
  content: "";
  display: table;
  clear: both;
}

a {
  color: #5D6975;
  text-decoration: underline;
}

body {
  position: relative;
  width: 21cm;  
  height: 29.7cm; 
  margin: 0 auto; 
  color: #001028;
  background: #FFFFFF; 
  font-family: Arial, sans-serif; 
  font-size: 12px; 
  font-family: Arial;
}

header {
  padding: 10px 0;
  margin-bottom: 30px;
}

#logo {
  text-align: center;
  margin-bottom: 10px;
}

#logo img {
  width: 90px;
}

h1 {
  border-top: 1px solid  #5D6975;
  border-bottom: 1px solid  #5D6975;
  color: #5D6975;
  font-size: 2.4em;
  line-height: 1.4em;
  font-weight: normal;
  text-align: center;
  margin: 0 0 20px 0;
  background: url(../images/dimension.png);
}

#project {
  float: left;
}

#project span {
  color: #5D6975;
  text-align: right;
  width: 52px;
  margin-right: 10px;
  display: inline-block;
  font-size: 0.8em;
}

#company {
  float: right;
  text-align: right;
}

#project div,
#company div {
  white-space: nowrap;        
}

table {
  width: 100%;
  border-collapse: collapse;
  border-spacing: 0;
  margin-bottom: 20px;
}

table tr:nth-child(2n-1) td {
  background: #F5F5F5;
}

table th,
table td {
  text-align: center;
}

table th {
  padding: 5px 20px;
  color: #5D6975;
  border-bottom: 1px solid #C1CED9;
  white-space: nowrap;        
  font-weight: normal;
}

table .service,
table .desc {
  text-align: left;
}

table td {
  padding: 20px;
  text-align: right;
}

table td.service,
table td.desc {
  vertical-align: top;
}

table td.unit,
table td.qty,
table td.total {
  font-size: 1.2em;
}

table td.grand {
  border-top: 1px solid #5D6975;;
}

#notices .notice {
  color: #5D6975;
  font-size: 1.2em;
}

footer {
  color: #5D6975;
  width: 100%;
  height: 30px;
  position: absolute;
  bottom: 0;
  border-top: 1px solid #C1CED9;
  padding: 8px 0;
  text-align: center;
}
  </style>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/new_planner.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Croffers</title>

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <%= csrf_meta_tags %>
    <%= render 'shared/ga' %>
 </head>

  <body>
    <%= render 'shared/navbar' %>

    <div id="planner">
      <%= yield %>
    </div>

    <script type="text/javascript">
      var markers = L.markerClusterGroup({animate: false});
      var map = L.map('map', { center: [44.5435052132082, 16.50146484375],
      zoom: 6});

      L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap</a> contributors'
      }).addTo(map);

     $(window).on('load', function () {
       map.addLayer(markers);
     });
    </script>
  </body>
</html>

app/views/layouts/new_session.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Croffers</title>

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <%= csrf_meta_tags %>
    <%= render 'shared/ga' %>
 </head>

  <body>
    <%= render 'shared/navbar' %>
    <div id="planner">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/new_trip.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Croffers</title>

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <%= csrf_meta_tags %>
    <%= render 'shared/ga' %>
 </head>

  <body>
    <%= render 'shared/navbar' %>
    <div id="planner">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/reservation.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <title>Invoice PDF</title>
    <meta charset="utf-8"/>
    <meta content="0.25in" name="pdfkit-margin_top"/>
    <meta content="0.25in" name="pdfkit-margin_right"/>
    <meta content="0.25in" name="pdfkit-margin_bottom"/>
    <meta content="0.25in" name="pdfkit-margin_left"/>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <style>
    
    .clearfix:after {
  content: "";
  display: table;
  clear: both;
}

a {
  color: #5D6975;
  text-decoration: underline;
}

body {
  position: relative;
  width: 21cm;  
  height: 29.7cm; 
  margin: 0 auto; 
  color: #001028;
  background: #FFFFFF; 
  font-family: Arial, sans-serif; 
  font-size: 12px; 
  font-family: Arial;
}

header {
  padding: 10px 0;
  margin-bottom: 30px;
}

#logo {
  text-align: center;
  margin-bottom: 10px;
}

#logo img {
  width: 90px;
}

h1 {
  border-top: 1px solid  #5D6975;
  border-bottom: 1px solid  #5D6975;
  color: #5D6975;
  font-size: 2.4em;
  line-height: 1.4em;
  font-weight: normal;
  text-align: center;
  margin: 0 0 20px 0;
  background: url(../images/dimension.png);
}

#project {
  float: left;
}

#project span {
  color: #5D6975;
  text-align: right;
  width: 52px;
  margin-right: 10px;
  display: inline-block;
  font-size: 0.8em;
}

#company {
  float: right;
  text-align: right;
}

#project div,
#company div {
  white-space: nowrap;        
}

table {
  width: 100%;
  border-collapse: collapse;
  border-spacing: 0;
  margin-bottom: 20px;
}

table tr:nth-child(2n-1) td {
  background: #F5F5F5;
}

table th,
table td {
  text-align: center;
}

table th {
  padding: 5px 20px;
  color: #5D6975;
  border-bottom: 1px solid #C1CED9;
  white-space: nowrap;        
  font-weight: normal;
}

table .service,
table .desc {
  text-align: left;
}

table td {
  padding: 20px;
  text-align: right;
}

table td.service,
table td.desc {
  vertical-align: top;
}

table td.unit,
table td.qty,
table td.total {
  font-size: 1.2em;
}

table td.grand {
  border-top: 1px solid #5D6975;;
}

#notices .notice {
  color: #5D6975;
  font-size: 1.2em;
}

footer {
  color: #5D6975;
  width: 100%;
  height: 30px;
  position: absolute;
  bottom: 0;
  border-top: 1px solid #C1CED9;
  padding: 8px 0;
  text-align: center;
}
  </style>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Croffers</title>

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <%= csrf_meta_tags %>
    <%= render 'shared/ga' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <%= yield %>
  </body>
</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Croffers</title>

  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    'static', media: 'all' %>
  <%= javascript_include_tag 'static' %>

  <%= csrf_meta_tags %>
  <%= render 'shared/ga' %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/layouts/user_profile.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Croffers</title>

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <%= csrf_meta_tags %>
    <%= render 'shared/ga' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <div id="profile-navbar">
      <div class="container-fluid">
				<ul>
					<% if current_user.is_business? %>
						<li id="profile-navbar-listings">
							<%= link_to 'Vaše ponude', user_listings_path, class: 'cool-link-profile' %>
						</li>
					<% end %>
					
					<li id="profile-navbar-packages">
						<%= link_to 'Paketi', reservation_packages_path, class: 'cool-link-profile' %>
					</li>
					
					<% if current_user.is_business? %>
						<li id="profile-navbar-reservations">
							<%= link_to 'Rezervacije', reservations_path, class: 'cool-link-profile' %>
						</li>
					<% end %>
					
					<li id="profile-navbar-payments">
						<%= link_to 'Plaćanja', payments_path, class: 'cool-link-profile' %>
					</li>
					
					<li id="profile-navbar-inbox">
						<%= link_to 'Poruke', message_threads_path, class: 'cool-link-profile' %>
					</li>
					
          <li id="profile-navbar-trips">
            <%= link_to 'Trips', trips_path, class: 'cool-link-profile' %>
          </li>

					<li id="profile-navbar-profile">
						<%= link_to 'Profil', edit_user_profile_path, class: 'cool-link-profile' %>
					</li>

				</ul>
      </div>
    </div>

    <div id="profile-main">
      <%= yield %>
    </div>
  </body>
</html>
<style type="text/css">

.cool-link-profile {
  display: inline-block;
  color: #969696;
  text-decoration: none;
}

.cool-link-profile::after {
  content: '';
  display: block;
  width: 0px;
  height: 1px;
  margin: 10px 0px;
  background: #ee365c;
  transition: width .3s;
  border-bottom: 2px solid #ee365c;
}

.cool-link-profile:hover::after {
  width: 100%;
  //transition: width .3s;
}
</style>
<script>
  $('#profile-navbar div ul li a').each(function(){
  var url = window.location.pathname,
    urlRegExp = new RegExp(url.replace(/\/$/,''));
    if(urlRegExp.test(this.href)){
      $(this).parent().addClass('active');  
    }
  });
</script>